tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/python'
tap 'homebrew/science'
tap 'neovim/neovim'
tap 'rogual/neovim-dot-app'
brew 'ack'
brew 'readline'
brew 'openssl', args: ['universal']
brew 'envchain'
brew 'git'
brew 'gnupg'
brew 'pinentry'
brew 'gpg-agent'
brew 'gnupg2'
brew 'graphviz'
brew 'libtool', args: ['universal']
brew 'jq'
brew 'keybase'
brew 'md5sha1sum'
brew 'node'
brew 'terragrunt'
brew 'youtube-dl'
brew 'neovim/neovim/neovim', args: ['HEAD']
cask 'alfred'
cask 'dropbox'
cask 'google-chrome'
cask 'imageoptim'
cask 'istat-menus'
cask 'iterm2'
cask 'monodraw'
cask 'screenflow'
cask 'slack'
cask 'spotify'
