#!/bin/bash
#
# Add a new user to Gruntwork via Zapier.
# Note: Does not add the user to GitHub
#

set -e

USER_CREATOR_EMAIL="josh@gruntwork.io"

TYPE_DED_SUPPORT_ABBR="pro"
TYPE_DED_SUPPORT="dedicated-support"

TYPE_SUB_ONLY_ABBR="std"
TYPE_SUB_ONLY="subscription-only"

PASS_PROP_ADD_USER_PASSWORD="gruntwork/zapier-password"
PASS_PROP_ADD_USER_URL="gruntwork/zapier-url"

type_abbr="$1"
first_name="$2"
last_name="$3"
email="$4"

function error_msg {
    local -r message="$1"
    echo "ERROR: $message"
    exit 1
}

function usage {
    echo "Usage: add-user <$TYPE_DED_SUPPORT | $TYPE_SUB_ONLY> <first-name> <last-name> <email>"
}

function validate_arg {
    local -r arg_name="$1"
    local -r arg_val="$2"

    if [[ "$arg_val" == "" ]]; then 
        usage
        error_msg "The argument \"$arg_name\" must be non-empty."
    fi
}

function add_user {
    local -r type="$1"
    local -r first_name="$2"
    local -r last_name="$3"
    local -r email="$4"
    local type

    curl \
    --request POST \
    --header "Content-Type: application/json" \
    --data "{
                \"firstName\": \"$first_name\",
                \"lastName\": \"$last_name\",
                \"email\": \"$email\",
                \"type\": \"$type\",
                \"creator-email\": \"$USER_CREATOR_EMAIL\",
                \"password\": \"$(pass $PASS_PROP_ADD_USER_PASSWORD)\"
            }" \
    $(pass $PASS_PROP_ADD_USER_URL)
}

validate_arg "<type>" "$type_abbr"
validate_arg "<first-name>" "$first_name"
validate_arg "<last-name>" "$last_name"
validate_arg "<email>" "$email"

if [[ "$type_abbr" == "$TYPE_DED_SUPPORT_ABBR" ]]; then
    add_user "$TYPE_DED_SUPPORT" "$first_name" "$last_name" "$email"    
elif [[ "$type_abbr" == "$TYPE_SUB_ONLY_ABBR" ]]; then
    add_user "$TYPE_SUB_ONLY" "$first_name" "$last_name" "$email"    
else
   usage
   error_msg "Type was \"$type_abbr\", but must be one of $TYPE_DED_SUPPORT_SHORT or $TYPE_SUB_ONLY_SHORT."
fi