#!/bin/bash
#
# Add a new user to Gruntwork via Zapier.
# Note: Does not add the user to GitHub
#

set -e

USER_CREATOR_EMAIL="josh@gruntwork.io"

TYPE_DED_SUPPORT="dedicated-support"
TYPE_SUB_ONLY="subscription-only"

PASS_PROP_ADD_USER_PASSWORD="gruntwork/zapier-password"
PASS_PROP_ADD_USER_URL="gruntwork/zapier-url"

first_name="$1"
last_name="$2"
email="$3"
type="$4"

function error_msg {
    local -r message="$1"
    echo "ERROR: $message"
    exit 1
}

function usage {
    echo "Usage: add-user <first-name> <last-name> <email> <$TYPE_DED_SUPPORT | $TYPE_SUB_ONLY>"
}

function validate_arg {
    local -r arg_name="$1"
    local -r arg_val="$2"

    if [[ "$arg_val" == "" ]]; then 
        usage
        error_msg "The argument \"$arg_name\" must be non-empty."
    fi
}

function add_user {
    local -r first_name="$1"
    local -r last_name="$2"
    local -r email="$3"
    local -r type="$4"

    curl \
    --request POST \
    --header "Content-Type: application/json" \
    --data "{
                \"firstName\": \"$first_name\",
                \"lastName\": \"$last_name\",
                \"email\": \"$email\",
                \"type\": \"$type\",
                \"creator-email\": \"$USER_CREATOR_EMAIL\",
                \"password\": \"$(pass $PASS_PROP_ADD_USER_PASSWORD)\"
            }" \
    $(pass $PASS_PROP_ADD_USER_URL)
}

validate_arg "<first-name>" "$first_name"
validate_arg "<last-name>" "$last_name"
validate_arg "<email>" "$email"
validate_arg "<type>" "$type"

if [[ "$type" != "$TYPE_DED_SUPPORT" ]] && [[ "$type" != "$TYPE_SUB_ONLY" ]]; then
   usage
   error_msg "Type was \"$type\", but must be one of $TYPE_DED_SUPPORT or $TYPE_SUB_ONLY."
fi

add_user "$first_name" "$last_name" "$email" "$type"
